In [3]:
import torch
import numpy as np

In [4]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

In [6]:
t_a = torch.tensor(a)
t_a

tensor([1, 2, 3])

In [7]:
t_b = torch.from_numpy(b)
t_b

tensor([4, 5, 6], dtype=torch.int32)

In [8]:
t_ones = torch.ones(2, 3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
t_zeros = torch.zeros(2, 3)
t_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
t_rand = torch.rand(2,3)
t_rand

tensor([[0.6842, 0.1457, 0.3651],
        [0.6122, 0.8650, 0.3441]])

In [11]:
t_tr = torch.transpose(t_rand, 0, 1)
t_tr

tensor([[0.6842, 0.6122],
        [0.1457, 0.8650],
        [0.3651, 0.3441]])

In [12]:
t_zeros_ = torch.zeros(10)
t_zeros_

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
t_zeros_reshape = t_zeros_.reshape(5, 2)
t_zeros_reshape

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
t = torch.zeros(1, 2, 1, 4, 1)
t.shape

torch.Size([1, 2, 1, 4, 1])

In [17]:
# for reducing unnecessary dimensions
t_sqz = torch.squeeze(t, 2)
t_sqz.shape

torch.Size([1, 2, 4, 1])

In [23]:
torch.manual_seed(1)

In [27]:
t = torch.rand(5, 2)
t

tensor([[0.3138, 0.1980],
        [0.4162, 0.2843],
        [0.3398, 0.5239],
        [0.7981, 0.7718],
        [0.0112, 0.8100]])

In [28]:
t1 = 2*t - 1
t1

tensor([[-0.3724, -0.6040],
        [-0.1676, -0.4313],
        [-0.3204,  0.0479],
        [ 0.5961,  0.5435],
        [-0.9776,  0.6199]])

In [30]:
t2 = torch.normal(mean=0, std=1, size=(5, 2))
t2

tensor([[ 0.3455,  0.5046],
        [ 1.8213, -0.1814],
        [-0.9515,  0.4057],
        [-1.5164,  0.7322],
        [ 2.2820, -1.2080]])

In [31]:
t3 = torch.multiply(t1, t2)
t3

tensor([[-0.1287, -0.3047],
        [-0.3053,  0.0783],
        [ 0.3049,  0.0194],
        [-0.9040,  0.3980],
        [-2.2307, -0.7489]])

In [34]:
# the axis params has value 0 for columns and 1 for rows
t4 = torch.mean(t1, axis=0)
t4

tensor([-0.2484,  0.0352])

In [36]:
torch.cuda.is_available()

True